Repository Somesh-Dahatonde/Html-form, pull requests merged in 2022-10, with the labels that each got.

#3 Updated and Fixed Button CSS
  form.html
  image/bg.jpg
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#4 Impove Button UI
  style.css
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#6 first commit
  form.html
  script.js
  style.css
Labels: good first issue, hacktoberfest-accepted

#5 added sign up form
  signup/css/style.css
  signup/images/Abhi Tyagi gif.gif
  signup/index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 footer tag add and resonsive website
  form.html
  style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
